fix(*): check for key already exists errors only

diff --git a/database/bin/boot b/database/bin/boot
--- a/database/bin/boot
+++ b/database/bin/boot
@@ -28,9 +28,10 @@ sleep $(($ETCD_TTL+1))
 
 function etcd_set_default {
   set +e
-  etcdctl --no-sync -C $ETCD mk $ETCD_PATH/$1 $2 >/dev/null 2>&1
-  if [[ $? -ne 0 && $? -ne 4 ]]; then
-    echo "etcd_set_default: an etcd error occurred. aborting..."
+  ERROR="$(etcdctl --no-sync -C $ETCD mk $ETCD_PATH/$1 $2 2>&1 >/dev/null)"
+  if [[ $? -ne 0 && $(echo $ERROR | grep -ive "key already exists") ]]; then
+    echo "etcd_set_default: an etcd error occurred ($ERROR)"
+    echo "aborting..."
     exit 1
   fi
   set -e
