feat(builder): disable simultaneous push in the same repository

diff --git a/builder/image/templates/gitreceive b/builder/image/templates/gitreceive
--- a/builder/image/templates/gitreceive
+++ b/builder/image/templates/gitreceive
@@ -42,19 +42,30 @@ EOF
   pre-receive)
     while read oldrev newrev refname
     do
-      # check for authorization on this repo
-      $GITHOME/receiver "$RECEIVE_REPO" "$newrev" "$RECEIVE_USER" "$RECEIVE_FINGERPRINT"
-      rc=$?
-      if [[ $rc != 0 ]] ; then
-        echo "      ERROR: failed on rev $newrev - push denied"
-        exit $rc
-      fi
-      # builder assumes that we are running this script from $GITHOME
-      cd $GITHOME
-      # if we're processing a receive-pack on an existing repo, run a build
-      if [[ $SSH_ORIGINAL_COMMAND == git-receive-pack* ]]; then
-        # SECURITY: git user runs the builder as root (for docker access)
-        sudo $GITHOME/builder $RECEIVE_USER $RECEIVE_REPO $newrev 2>&1 | strip_remote_prefix
+      LOCKFILE="/tmp/$RECEIVE_REPO.lock"
+      if ( set -o noclobber; echo "$$" > "$LOCKFILE" ) 2> /dev/null; then
+        trap 'rm -f "$LOCKFILE"; exit $?' INT TERM EXIT
+
+        # check for authorization on this repo
+        $GITHOME/receiver "$RECEIVE_REPO" "$newrev" "$RECEIVE_USER" "$RECEIVE_FINGERPRINT"
+        rc=$?
+        if [[ $rc != 0 ]] ; then
+          echo "      ERROR: failed on rev $newrev - push denied"
+          exit $rc
+        fi
+        # builder assumes that we are running this script from $GITHOME
+        cd $GITHOME
+        # if we're processing a receive-pack on an existing repo, run a build
+        if [[ $SSH_ORIGINAL_COMMAND == git-receive-pack* ]]; then
+          # SECURITY: git user runs the builder as root (for docker access)
+          sudo $GITHOME/builder $RECEIVE_USER $RECEIVE_REPO $newrev 2>&1 | strip_remote_prefix
+        fi
+
+        rm -f "$LOCKFILE"
+        trap - INT TERM EXIT
+      else
+        echo "Another git push is ongoing. Aborting..."
+        exit 1
       fi
     done
     ;;
