fix(builder): validate that properly formed slugs are added correctly

diff --git a/builder/templates/builder b/builder/templates/builder
--- a/builder/templates/builder
+++ b/builder/templates/builder
@@ -105,6 +105,8 @@ fi
 # if no Dockerfile is present, use slugbuilder to compile a heroku slug
 # and write out a Dockerfile to use that slug
 if [ ! -f Dockerfile ]; then
+    # FIXME: validate slugs were added correctly to the image
+    VALIDATE_IMAGE=1
     # build option string to send to slugbuilder
     BUILD_OPTS=("$CONFIG")
 
@@ -137,6 +139,15 @@ echo "ENV GIT_SHA $GIT_SHA" >> Dockerfile
 echo
 puts-step "Building Docker image"
 docker build -t $TMP_IMAGE . 2>&1
+
+# FIXME: validate Docker image to ensure slug is not malformed
+if [[ $VALIDATE_IMAGE ]]; then
+    if [[ "$(docker history $TMP_IMAGE | grep ADD | head -n1 | awk {'print $11'})" == "0" ]]; then
+        puts-warn "Malformed Docker image, aborting build."
+        exit 1
+    fi
+fi
+
 puts-step "Pushing image to private registry"
 docker push $TMP_IMAGE  &>/dev/null
 echo
