refactor(bin/boot) consolidate into a single script with debug and optional publishing

diff --git a/controller/bin/boot b/controller/bin/boot
--- a/controller/bin/boot
+++ b/controller/bin/boot
@@ -3,15 +3,16 @@
 # This script is designed to be run inside the container
 #
 
+# fail hard and fast even on pipelines
+set -eo pipefail
+
+# set debug based on envvar
+[[ $DEBUG ]] && set -x
+
 # configure etcd
 export ETCD=${ETCD:-172.17.42.1:4001}
 export ETCD_PATH=${ETCD_PATH:-/deis/controller}
 export ETCD_TTL=${ETCD_TTL:-10}
-
-# configure service discovery
-export HOST=${HOST:-localhost}
-export PORT=${PORT:-8000}
-export PROTO=${PROTO:-tcp}
 
 # wait for etcd to be available
 until etcdctl -C $ETCD ls >/dev/null; do
@@ -23,7 +24,11 @@ done
 sleep $(($ETCD_TTL+1))
 
 # seed initial service configuration if necessary
-$(dirname ${BASH_SOURCE[0]})/seed >/dev/null 2>&1
+if ! etcdctl -C $ETCD ls $ETCD_PATH >/dev/null 2>/dev/null; then
+	etcdctl -C $ETCD set $ETCD_PATH/protocol ${DEIS_PROTOCOL:-http}
+	etcdctl -C $ETCD set $ETCD_PATH/secretKey ${DEIS_SECRET_KEY:-`openssl rand -base64 64 | tr -d '\n'`}
+	etcdctl -C $ETCD set $ETCD_PATH/builderKey ${DEIS_BUILDER_KEY:-`openssl rand -base64 64 | tr -d '\n'`}
+fi
 
 # wait for confd to run once and install initial templates
 until confd -onetime -node $ETCD -config-file /app/confd.toml 2>/dev/null; do
@@ -38,14 +43,23 @@ while grep -q '<no value>' /templates/confd_settings.py; do
        sleep $(($ETCD_TTL/2))  # sleep for half the TTL
 done
 
-# spawn the service in the background
-$(dirname ${BASH_SOURCE[0]})/start &
-SERVICE_PID=$!
+cd /app
+
+# run an idempotent database migration
+sudo -E -u deis ./manage.py syncdb --migrate --noinput
+
+# spawn celery worker in the background
+sudo -E -u deis celery worker --app=deis --loglevel=INFO --workdir=/app --pidfile=/tmp/celery.pid &
+CELERY_PID=$!
+
+# spawn a gunicorn server in the foreground
+sudo -E -u deis ./manage.py run_gunicorn -b 0.0.0.0 -w 8 -t 600 -n deis --log-level debug --pid=/tmp/gunicorn.pid --preload & # -k gevent
+GUNICORN_PID=$!
 
 # smart shutdown on SIGINT and SIGTERM
 function on_exit() {
-	kill -TERM $SERVICE_PID
-	wait $SERVICE_PID 2>/dev/null
+	kill -TERM $CELERY_PID $GUNICORN_PID
+	wait $CELERY_PID $GUNICORN_PID 2>/dev/null
 }
 trap on_exit INT TERM
 
@@ -53,10 +67,27 @@ trap on_exit INT TERM
 confd -node $ETCD -config-file /app/confd.toml &
 CONFD_PID=$!
 
-# wait for the service to become available
-sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PORT\" && \$1 ~ \"$PROTO.?\"") ]] ; do sleep 1; done
+# publish the service to etcd using the injected HOST and PORT
+if [[ ! -z $PUBLISH ]]; then
 
-# as long as the service remains up, keep publishing to etcd with a TTL
-$(dirname ${BASH_SOURCE[0]})/publish &
+	# configure service discovery
+	HOST=${HOST:-localhost}
+	PORT=${PORT:-8000}
+	PROTO=${PROTO:-tcp}
+
+	# wait for the service to become available on PUBLISH port
+	sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do sleep 1; done
+
+	# while the port is listening, publish to etcd
+	while [[ ! -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do
+		etcdctl -C $ETCD set $ETCD_PATH/host $HOST --ttl $ETCD_TTL >/dev/null
+		etcdctl -C $ETCD set $ETCD_PATH/port $PORT --ttl $ETCD_TTL >/dev/null
+		sleep $(($ETCD_TTL/2)) # sleep for half the TTL
+	done
+
+	# if the loop quits, something went wrong
+	exit 1
+
+fi
 
 wait
diff --git a/database/bin/boot b/database/bin/boot
--- a/database/bin/boot
+++ b/database/bin/boot
@@ -3,15 +3,16 @@
 # This script is designed to be run inside the container
 #
 
+# fail hard and fast even on pipelines
+set -eo pipefail
+
+# set debug based on envvar
+[[ $DEBUG ]] && set -x
+
 # configure etcd
-export ETCD=${ETCD:-127.0.0.1:4001}
+export ETCD=${ETCD:-172.17.42.1:4001}
 export ETCD_PATH=${ETCD_PATH:-/deis/database}
 export ETCD_TTL=${ETCD_TTL:-10}
-
-# configure service discovery
-export HOST=${HOST:-localhost}
-export PORT=${PORT:-5432}
-export PROTO=${PROTO:-tcp}
 
 # initialize data volume
 if [[ ! -d /var/lib/postgresql/9.3/main ]]; then
@@ -30,7 +31,14 @@ done
 sleep $(($ETCD_TTL+1))
 
 # seed initial service configuration if necessary
-$(dirname ${BASH_SOURCE[0]})/seed >/dev/null
+if ! etcdctl -C $ETCD ls $ETCD_PATH >/dev/null 2>/dev/null; then
+	etcdctl -C $ETCD set $ETCD_PATH/engine postgresql_psycopg2
+	etcdctl -C $ETCD set $ETCD_PATH/adminUser ${PG_ADMIN_USER:-postgres}
+	etcdctl -C $ETCD set $ETCD_PATH/adminPass ${PG_ADMIN_PASS:-changeme123}
+	etcdctl -C $ETCD set $ETCD_PATH/user ${PG_USER_NAME:-deis} >/dev/null
+	etcdctl -C $ETCD set $ETCD_PATH/password ${PG_USER_PASS:-changeme123}
+	etcdctl -C $ETCD set $ETCD_PATH/name ${PG_USER_DB:-deis}
+fi
 
 # wait for confd to run once and install initial templates
 until confd -onetime -node $ETCD -config-file /app/confd.toml; do
@@ -38,8 +46,11 @@ until confd -onetime -node $ETCD -config-file /app/confd.toml; do
 	sleep $(($ETCD_TTL/2))  # sleep for half the TTL
 done
 
-# spawn the service in the background
-$(dirname ${BASH_SOURCE[0]})/start &
+# run the service in the background
+sudo -i -u postgres /usr/lib/postgresql/9.3/bin/postgres \
+                    -c config-file=${PG_CONFIG:-/etc/postgresql/9.3/main/postgresql.conf} \
+                    -c listen-addresses=${PG_LISTEN:-*} &
+
 SERVICE_PID=$!
 
 # smart shutdown on SIGINT and SIGTERM
@@ -54,12 +65,32 @@ confd -node $ETCD -config-file /app/confd.toml &
 CONFD_PID=$!
 
 # wait for the service to become available
-sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PORT\" && \$1 ~ \"$PROTO.?\"") ]] ; do sleep 1; done
+sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".5432\" && \$1 ~ \"tcp.?\"") ]] ; do sleep 1; done
 
 # perform a one-time reload to populate database entries
 /usr/local/bin/reload
 
-# as long as the service remains up, keep publishing to etcd with a TTL
-$(dirname ${BASH_SOURCE[0]})/publish &
+# publish the service to etcd using the injected HOST and PORT
+if [[ ! -z $PUBLISH ]]; then
+
+	# configure service discovery
+	HOST=${HOST:-localhost}
+	PORT=${PORT:-5432}
+	PROTO=${PROTO:-tcp}
+
+	# wait for the service to become available on PUBLISH port
+	sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do sleep 1; done
+
+	# while the port is listening, publish to etcd
+	while [[ ! -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do
+		etcdctl -C $ETCD set $ETCD_PATH/host $HOST --ttl $ETCD_TTL >/dev/null
+		etcdctl -C $ETCD set $ETCD_PATH/port $PORT --ttl $ETCD_TTL >/dev/null
+		sleep $(($ETCD_TTL/2)) # sleep for half the TTL
+	done
+
+	# if the loop quits, something went wrong
+	exit 1
+
+fi
 
 wait
diff --git a/registry/bin/boot b/registry/bin/boot
--- a/registry/bin/boot
+++ b/registry/bin/boot
@@ -3,18 +3,19 @@
 # This script is designed to be run inside the container
 #
 
+# fail hard and fast even on pipelines
+set -eo pipefail
+
+# set debug based on envvar
+[[ $DEBUG ]] && set -x
+
 # configure etcd
-export ETCD=${ETCD:-127.0.0.1:4001}
+export ETCD=${ETCD:-172.17.42.1:4001}
 export ETCD_PATH=${ETCD_PATH:-/deis/registry}
 export ETCD_TTL=${ETCD_TTL:-10}
 
-# configure service discovery
-export HOST=${HOST:-localhost}
-export PORT=${PORT:-5000}
-export PROTO=${PROTO:-tcp}
-
 # run.sh requires $REGISTRY_PORT
-export REGISTRY_PORT=$PORT
+export REGISTRY_PORT=${PORT:-5000}
 
 # wait for etcd to be available
 until etcdctl -C $ETCD ls >/dev/null; do
@@ -26,7 +27,10 @@ done
 sleep $(($ETCD_TTL+1))
 
 # seed initial service configuration if necessary
-$(dirname ${BASH_SOURCE[0]})/seed >/dev/null
+if ! etcdctl -C $ETCD ls $ETCD_PATH >/dev/null 2>/dev/null; then
+	etcdctl -C $ETCD set $ETCD_PATH/protocol http >/dev/null
+	etcdctl -C $ETCD set $ETCD_PATH/secretKey ${REGISTRY_SECRET_KEY:-`openssl rand -base64 64 | tr -d '\n'`} >/dev/null
+fi
 
 # wait for confd to run once and install initial templates
 until confd -onetime -node $ETCD -config-file /app/confd.toml; do
@@ -34,11 +38,10 @@ until confd -onetime -node $ETCD -config-file /app/confd.toml; do
 	sleep $(($ETCD_TTL/2))  # sleep for half the TTL
 done
 
-# fail hard and fast even on pipelines
-set -eo pipefail
-
 # spawn the service in the background
-$(dirname ${BASH_SOURCE[0]})/start &
+cd /docker-registry
+./setup-configs.sh
+sudo -E -u registry ./run.sh &
 SERVICE_PID=$!
 
 # smart shutdown on SIGINT and SIGTERM
@@ -52,10 +55,27 @@ trap on_exit INT TERM
 confd -node $ETCD -config-file /app/confd.toml &
 CONFD_PID=$!
 
-# wait for the service to become available
-sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PORT\" && \$1 ~ \"$PROTO.?\"") ]] ; do sleep 1; done
+# publish the service to etcd using the injected HOST and PORT
+if [[ ! -z $PUBLISH ]]; then
 
-# as long as the service remains up, keep publishing to etcd with a TTL
-$(dirname ${BASH_SOURCE[0]})/publish &
+	# configure service discovery
+	HOST=${HOST:-localhost}
+	PORT=${PORT:-5000}
+	PROTO=${PROTO:-tcp}
+
+	# wait for the service to become available on PUBLISH port
+	sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do sleep 1; done
+
+	# while the port is listening, publish to etcd
+	while [[ ! -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do
+		etcdctl -C $ETCD set $ETCD_PATH/host $HOST --ttl $ETCD_TTL >/dev/null
+		etcdctl -C $ETCD set $ETCD_PATH/port $PORT --ttl $ETCD_TTL >/dev/null
+		sleep $(($ETCD_TTL/2)) # sleep for half the TTL
+	done
+
+	# if the loop quits, something went wrong
+	exit 1
+
+fi
 
 wait
diff --git a/router/bin/boot b/router/bin/boot
--- a/router/bin/boot
+++ b/router/bin/boot
@@ -3,6 +3,9 @@
 # This script is designed to be run inside the container
 #
 
+# fail hard and fast even on pipelines
+set -eo pipefail
+
 # set debug based on envvar
 [[ $DEBUG ]] && set -x
 
@@ -10,11 +13,6 @@
 export ETCD=${ETCD:-172.17.42.1:4001}
 export ETCD_PATH=${ETCD_PATH:-/deis/router}
 export ETCD_TTL=${ETCD_TTL:-10}
-
-# configure service discovery
-export HOST=${HOST:-localhost}
-export PORT=${PORT:-80}
-export PROTO=${PROTO:-tcp}
 
 # wait for etcd to be available
 until etcdctl -C $ETCD ls >/dev/null; do
@@ -26,7 +24,12 @@ done
 sleep $(($ETCD_TTL+1))
 
 # seed initial service configuration if necessary
-$(dirname ${BASH_SOURCE[0]})/seed >/dev/null 2>&1
+if ! etcdctl -C $ETCD ls /deis/services >/dev/null 2>&1; then
+	etcdctl -C $ETCD mkdir /deis/services
+	etcdctl -C $ETCD set $ETCD_PATH/port ${PORT:-80}
+	etcdctl -C $ETCD set $ETCD_PATH/workerConnections 1024
+	etcdctl -C $ETCD set $ETCD_PATH/workerProcesses 2
+fi
 
 # wait for confd to run once and install initial templates
 until confd -onetime -node $ETCD -config-file /app/confd.toml; do
@@ -48,5 +51,28 @@ trap on_exit INT TERM
 # spawn confd in the background to update services based on etcd changes
 confd -node $ETCD -config-file /app/confd.toml &
 CONFD_PID=$!
+
+# publish the service to etcd using the injected HOST and PORT
+if [[ ! -z $PUBLISH ]]; then
+
+	# configure service discovery
+	HOST=${HOST:-localhost}
+	PORT=${PORT:-80}
+	PROTO=${PROTO:-tcp}
+
+	# wait for the service to become available on PUBLISH port
+	sleep 1 && while [[ -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do sleep 1; done
+
+	# while the port is listening, publish to etcd
+	while [[ ! -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PUBLISH\" && \$1 ~ \"$PROTO.?\"") ]] ; do
+		etcdctl -C $ETCD set $ETCD_PATH/host $HOST --ttl $ETCD_TTL >/dev/null
+		etcdctl -C $ETCD set $ETCD_PATH/port $PORT --ttl $ETCD_TTL >/dev/null
+		sleep $(($ETCD_TTL/2)) # sleep for half the TTL
+	done
+
+	# if the loop quits, something went wrong
+	exit 1
+
+fi
 
 wait
